SUPABASE_URL = "https://supabase.com/dashboard/project/nzgdiyjdrfludykkzxiv/editor/17269"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56Z2RpeWpkcmZsdWR5a2t6eGl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMzYxNjQsImV4cCI6MjA2NzcxMjE2NH0.3lGOGA3FwOuLraw1Uv5-6BJ_iecrY5O9mN3RbXard7k"
